import type { Metadata } from "next";
import "./globals.css";
import PortfolioLayout from "@/Components/PortfolioLayout";
import ThemeProviderNext from "@/Components/ThemeProvider";
import local from "next/font/local"

const neueFont = local({
  src: "./NeueMontreal-Light.otf",
  variable: "--font-neue"
})
const neueFontRegular = local({
  src: "./PPNeueMontreal-Book.otf",
  variable: "--font-neue-regular"
})

const neueMono = local({
  src: "./PPNeueMontrealMono-Thin.otf",
  variable: "--font-neue-mono"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`
         ${neueFont.className} 
         ${neueFontRegular.variable}
         ${neueMono.variable} antialiased  `}>
        <ThemeProviderNext >
          <PortfolioLayout>
            {children}
          </PortfolioLayout>
        </ThemeProviderNext>
      </body>
    </html>
  );
}
