name: build worflow

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  build_pipeline:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: build job
    runs-on: ${{ matrix.os }}
    environment: deployment
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: installing dependencies
        run: npm ci
      - name: adding .env.local file
        run: echo "${{ secrets.SECRETS }}" > .env.local && cat .evn.local
      - name: build step
        run: |
          ls -la
          cat .env.local
          npm run build
