name: build worflow

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  build_pipeline:
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: build job
    runs-on: ${{ matrix.os }}
    environment: deployment
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node_version: 20
      - name: installing dependencies
        run: npm ci
      - name: build step
        run: |
          echo "${{ secrets.ENV_LOCAL}} > .env.local
          ls -la
          npm run build
